name: Deploy Frontend to Prod

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  deploy:
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch' && github.ref_name == 'main')

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Prepare target directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          key: ${{ secrets.SSH_PROD_KEY }}
          script: |
            sudo rm -rf /var/www/frontend-pioneer
            sudo mkdir -p /var/www/frontend-pioneer
            sudo chown $USER:$USER /var/www/frontend-pioneer
      
      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          key: ${{ secrets.SSH_PROD_KEY }}
          source: "frontend/dist"
          target: "/var/www/frontend-pioneer"
          strip_components: 2        

      - name: Set permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          key: ${{ secrets.SSH_PROD_KEY }}
          script: |
            find /var/www/frontend-pioneer -type f -exec chmod 644 {} \;
            find /var/www/frontend-pioneer -type d -exec chmod 755 {} \;
            sudo chown -R www-data:www-data /var/www/frontend-pioneer
            sudo nginx -t && sudo systemctl reload nginx
